docker push fix

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -50,9 +50,14 @@ jobs:
         password: ${{ secrets.DOCKER_PASSWORD }}
       # This step logs in to Docker Hub using provided secrets
 
-    - name: Build and push
-      uses: docker/build-push-action@v5
-      with:
-        context: ./app_python
-        push: true
-        tags: ${{ secrets.DOCKERHUB_USERNAME }}/khays-python-app:latest 
+    - name: Build Docker image
+      run: |
+        cd app_python/
+        docker build -t khays-python-app:latest .
+      # This step builds the Docker image for your application
+
+    - name: Push Docker image
+      run: |
+        cd app_python/
+        echo "Attempting to push Docker image..."
+        docker push khays-python-app:latest || echo "Docker push failed!"
